# Generated by Django 2.2 on 2020-12-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_auto_20201231_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='nPubDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
