# Generated by Django 2.2 on 2020-12-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_auto_20201231_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='nStatus',
            field=models.BooleanField(),
        ),
    ]
