# Generated by Django 2.2 on 2020-12-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_auto_20201231_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='nStatus',
            field=models.IntegerField(),
        ),
    ]
